spring.application.name=distributed-storage-system

#Request configurations
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
server.tomcat.max-swallow-size=500MB

# Metadata Database
spring.data.mongodb.uri=mongodb://localhost:27017/metadata_db

# Chunk Databases
chunk.db1.uri=mongodb://localhost:27018/chunk_db
chunk.db2.uri=mongodb://localhost:27019/chunk_db
chunk.db3.uri=mongodb://localhost:27020/chunk_db
chunk.db4.uri=mongodb://localhost:27021/chunk_db